### PR TITLE
Add ansible talk for August

### PR DESCRIPTION
**Pull request by kenfusion**

### CODE REVIEW

**Comment by mblayman** [comment]
@kenfusion Are you finish with this PR content or should I expect more commits down the pipe?

**Comment by kenfusion** [comment]
There might be more.  I'm on that, "good enough, but can be better" fence.

**Comment by mblayman** [comment]
Ok, let me know when you think you're done and then I can merge it.

**Comment by kenfusion** [comment]
I think I'm going to add this as a sub module and tinker with it that way.

**Pull request closed without merging**
